name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade "pip<24.1" "setuptools<70.0.0" wheel
          pip install "cython<3.0.0" buildozer

      - name: Setup Android SDK Licenses & Pre-cache
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | sdkmanager --licenses || true
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          cp -rf /usr/local/lib/android/sdk/licenses/* ~/.buildozer/android/platform/android-sdk/licenses/ || true
          yes | sdkmanager "build-tools;33.0.2" "platforms;android-33" "platform-tools" || true

      - name: Build Android APK
        run: |
          export CI=true
          export BUILDOZER_ALLOW_ROOT=1
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OKWin-AI-Predictor-APK
          path: bin/*.apk
